apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - git:
      repoURL: https://github.com/mervani/example-kubernetes-go-repo.git
      revision: main
      directories:
      - path: cluster-XXXX/tenants/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/mervani/example-kubernetes-go-repo.git 
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
