resources:
  - ../../base
generatorOptions:
  labels:
    type: generated
  annotations:
    note: generated

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: myappset
    target:
      kind: ApplicationSet
      name: cluster
